backend:
  name: github
  repo: BountyGA/my-product-site   # e.g. BountyGA/my-store
  branch: master                      # Your default branch
  base_url: https://my-product-site-cis.pages.dev/auth

media_folder: "public/uploads"       # Where uploaded files are stored in repo
public_folder: "/uploads"            # Public path for accessing uploaded files

collections:
  - name: "products"                 # Folder for collection
    label: "Products"                # Shown in CMS sidebar
    folder: "content/products"       # Location in repo for product files
    create: true                     # Allow new products
    slug: "{{slug}}"                 # Filename based on product name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
